language: scala
script:
 - git config --global user.email "example@example.com"
 - git config --global user.name "example"
 - echo '[ui]' > "$HOME/.hgrc"
 - echo 'username = example <example@example.com>' >> "$HOME/.hgrc"
 - sbt test
 - sbt publishLocal
 - sbt scripted
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
sudo: false
